<a href="https://colab.research.google.com/github/filipecarbonera/formacao_python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Documentação Numpy]('https://numpy.org/doc/stable/')

[Tipos de dados do Numpy]('https://numpy.org/doc/stable/user/basics.types.html')

In [1]:
import numpy as np

### **Exemplo:** Calculando a kilometragem média:

[Documentação loadtext do Numpy]("https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html")

In [2]:
km = np.loadtxt('https://raw.githubusercontent.com/filipecarbonera/formacao_python/main/dados/carros-km.txt')
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [3]:
anos = np.loadtxt('https://raw.githubusercontent.com/filipecarbonera/formacao_python/main/dados/carros-anos.txt', dtype=int)
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

In [4]:
km_media = km / (2022 - anos)
print(km_media)
print(type(km_media))

[2.33736842e+03 1.84258065e+02 1.16009375e+03 0.00000000e+00
 1.60981250e+03 1.07280000e+03 0.00000000e+00 5.96915385e+03
 8.26641667e+03 3.45254545e+03 6.42950000e+02 5.36800000e+02
 4.27490476e+03 0.00000000e+00 3.18900000e+03 1.92678333e+04
 4.64490000e+03 0.00000000e+00 6.18100000e+03 3.03460000e+03
 5.05965000e+03 0.00000000e+00 3.50282143e+03 3.32125806e+03
 0.00000000e+00 0.00000000e+00 9.65833333e+02 0.00000000e+00
 2.94240000e+03 3.04454839e+03 1.20652000e+03 1.97525926e+03
 4.43000000e+03 1.09058065e+03 1.13355000e+04 1.62870370e+03
 0.00000000e+00 0.00000000e+00 4.25076923e+02 0.00000000e+00
 1.03794444e+04 2.14536842e+03 0.00000000e+00 4.31510000e+03
 0.00000000e+00 4.87750000e+02 3.88583333e+03 1.14047619e+02
 0.00000000e+00 4.22889474e+03 6.58107692e+03 3.15600000e+03
 3.07800000e+03 5.87168750e+03 2.94541667e+03 2.89310714e+03
 7.96753333e+03 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 2.37790000e+04 4.40990909e+03
 4.80533333e+03 3.678807

In [5]:
_ # última variável guardada na memória.

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

### **Continuando:**

[Documentação Arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[Documentação List to Array]('https://numpy.org/doc/stable/reference/generated/numpy.array.html')

In [7]:
np.array([10,100,1000,10000])

array([   10,   100,  1000, 10000])

In [8]:
# Desempenho List
py_list = list(range(1000000))

# Desempenho Array
np_array = np.arange(1000000)

In [9]:
%time for _ in range(100): np_array *= 2

CPU times: user 57.6 ms, sys: 995 µs, total: 58.6 ms
Wall time: 59.3 ms


In [10]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 8.99 s, sys: 2.19 s, total: 11.2 s
Wall time: 11.7 s


### [Métodos do Numpy]('https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#array-mothods')

In [11]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.], [ 2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [12]:
dados.shape

(2, 5)

In [13]:
dados.ndim

2

In [14]:
dados.size

10

In [15]:
dados.size

10

In [16]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [17]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [18]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
contador.reshape((5, 2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
contador.reshape((5, 2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [23]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [24]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [25]:
np.array(info_carros)

array([44410,  5712, 37123,     0, 25757,  2003,  1991,  1990,  2019,
        2006])

In [26]:
np.array(info_carros).reshape((2, 5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [27]:
np.array(info_carros).reshape((5, 2))

array([[44410,  5712],
       [37123,     0],
       [25757,  2003],
       [ 1991,  1990],
       [ 2019,  2006]])

In [28]:
np.array(info_carros).reshape((5, 2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

### **Estatisticas com Numpy:**

In [31]:
anos = np.loadtxt('https://raw.githubusercontent.com/filipecarbonera/formacao_python/main/dados/carros-anos.txt', dtype=int)
km = np.loadtxt('https://raw.githubusercontent.com/filipecarbonera/formacao_python/main/dados/carros-km.txt')
valor = np.loadtxt('https://raw.githubusercontent.com/filipecarbonera/formacao_python/main/dados/carros-valor.txt')

In [33]:
anos.shape

(258,)

In [34]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [36]:
dataset.shape

(258, 3)

In [40]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [42]:
np.mean(dataset[:,1])

44499.41472868217

In [43]:
np.std(dataset[:,1])

39859.82699005149